//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.22 at 11:08:46 a. m. CDT 
//


package me.tell.mensajes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the me.tell.mensajes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: me.tell.mensajes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaludarRequest }
     * 
     */
    public SaludarRequest createSaludarRequest() {
        return new SaludarRequest();
    }

    /**
     * Create an instance of {@link ModificarSaludosResponse }
     * 
     */
    public ModificarSaludosResponse createModificarSaludosResponse() {
        return new ModificarSaludosResponse();
    }

    /**
     * Create an instance of {@link BorrarSaludosResponse }
     * 
     */
    public BorrarSaludosResponse createBorrarSaludosResponse() {
        return new BorrarSaludosResponse();
    }

    /**
     * Create an instance of {@link ModificarSaludosRequest }
     * 
     */
    public ModificarSaludosRequest createModificarSaludosRequest() {
        return new ModificarSaludosRequest();
    }

    /**
     * Create an instance of {@link BuscarSaludosResponse.Saludador }
     * 
     */
    public BuscarSaludosResponse.Saludador createBuscarSaludosResponseSaludador() {
        return new BuscarSaludosResponse.Saludador();
    }

    /**
     * Create an instance of {@link SaludarResponse }
     * 
     */
    public SaludarResponse createSaludarResponse() {
        return new SaludarResponse();
    }

    /**
     * Create an instance of {@link BuscarSaludosResponse }
     * 
     */
    public BuscarSaludosResponse createBuscarSaludosResponse() {
        return new BuscarSaludosResponse();
    }

    /**
     * Create an instance of {@link BuscarSaludosRequest }
     * 
     */
    public BuscarSaludosRequest createBuscarSaludosRequest() {
        return new BuscarSaludosRequest();
    }

    /**
     * Create an instance of {@link BorrarSaludosRequest }
     * 
     */
    public BorrarSaludosRequest createBorrarSaludosRequest() {
        return new BorrarSaludosRequest();
    }

}
