//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 03:16:31 p. m. CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tell.me/mensajes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package me.tell.mensajes;
