//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 06:25:22 p. m. CDT 
//


package me.tell.ventas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="empleadoV" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idproducto" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="precioU" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="enStock" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "empleadoV"
})
@XmlRootElement(name = "MostrarVentaResponse")
public class MostrarVentaResponse {

    @XmlElement(required = true)
    protected List<MostrarVentaResponse.EmpleadoV> empleadoV;

    /**
     * Gets the value of the empleadoV property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the empleadoV property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmpleadoV().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MostrarVentaResponse.EmpleadoV }
     * 
     * 
     */
    public List<MostrarVentaResponse.EmpleadoV> getEmpleadoV() {
        if (empleadoV == null) {
            empleadoV = new ArrayList<MostrarVentaResponse.EmpleadoV>();
        }
        return this.empleadoV;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idproducto" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="precioU" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="enStock" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idproducto",
        "nombre",
        "descripcion",
        "precioU",
        "enStock"
    })
    public static class EmpleadoV {

        protected int idproducto;
        @XmlElement(required = true)
        protected String nombre;
        @XmlElement(required = true)
        protected String descripcion;
        protected int precioU;
        @XmlElement(required = true)
        protected String enStock;

        /**
         * Gets the value of the idproducto property.
         * 
         */
        public int getIdproducto() {
            return idproducto;
        }

        /**
         * Sets the value of the idproducto property.
         * 
         */
        public void setIdproducto(int value) {
            this.idproducto = value;
        }

        /**
         * Gets the value of the nombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the descripcion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescripcion() {
            return descripcion;
        }

        /**
         * Sets the value of the descripcion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescripcion(String value) {
            this.descripcion = value;
        }

        /**
         * Gets the value of the precioU property.
         * 
         */
        public int getPrecioU() {
            return precioU;
        }

        /**
         * Sets the value of the precioU property.
         * 
         */
        public void setPrecioU(int value) {
            this.precioU = value;
        }

        /**
         * Gets the value of the enStock property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnStock() {
            return enStock;
        }

        /**
         * Sets the value of the enStock property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnStock(String value) {
            this.enStock = value;
        }

    }

}
