//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.23 at 04:30:55 p. m. CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tell.me/ventas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package me.tell.ventas;
