//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.16 at 02:16:40 p. m. CDT 
//


package org.example.ventas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.ventas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.ventas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RealizarVentaRequest }
     * 
     */
    public RealizarVentaRequest createRealizarVentaRequest() {
        return new RealizarVentaRequest();
    }

    /**
     * Create an instance of {@link ModificarVentaRequest }
     * 
     */
    public ModificarVentaRequest createModificarVentaRequest() {
        return new ModificarVentaRequest();
    }

    /**
     * Create an instance of {@link RealizarVentaResponse }
     * 
     */
    public RealizarVentaResponse createRealizarVentaResponse() {
        return new RealizarVentaResponse();
    }

    /**
     * Create an instance of {@link ModificarVentaResponse }
     * 
     */
    public ModificarVentaResponse createModificarVentaResponse() {
        return new ModificarVentaResponse();
    }

    /**
     * Create an instance of {@link EliminarVentaResponse }
     * 
     */
    public EliminarVentaResponse createEliminarVentaResponse() {
        return new EliminarVentaResponse();
    }

    /**
     * Create an instance of {@link EliminarVentaRequest }
     * 
     */
    public EliminarVentaRequest createEliminarVentaRequest() {
        return new EliminarVentaRequest();
    }

}
